use typst_tui_document::Motion;

use crate::compile::CompileResult;
use crate::export::ExportResult;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Pane {
    Explorer,
    Editor,
    Preview,
}

pub(crate) enum Action {
    Insert(char),
    InsertText(String),
    Backspace,
    Delete,
    Move(Motion),
    Select(Motion),
    SelectAll,
    Copy,
    Cut,
    PasteClipboard,
    Undo,
    Redo,
    Recompile,
    CompileFinished(CompileResult),
    ExportFinished(ExportResult),
    Resize,
    ProjectFilesChanged,
    FileWatchFailed(String),
    Tick,
    SwitchFocus,
    ToggleDiagnostics,
    NavigateDiagnostic(isize),
    MouseDown { column: u16, row: u16 },
    MouseDrag { column: u16, row: u16 },
    ScrollAt { column: u16, row: u16, lines: isize },
    ScrollPreviewPages(isize),
    ZoomPreview(isize),
    ToggleFullscreen,
    ToggleFileExplorer,
    OpenCommandPalette,
    OpenHelp,
    OpenGoToLine,
    OpenFind,
    OpenReplace,
    NewDocument,
    OpenFile,
    CloseOverlay,
    OverlayInput(char),
    OverlayInputText(String),
    OverlayBackspace,
    OverlayMove(isize),
    OverlaySubmit,
    SearchNext(bool),
    SearchToggleField,
    ReplaceCurrent,
    Save,
    RequestQuit,
    Quit,
    CancelQuit,
}
