[package]
name = "oxyst-compiler"
description = "Typst compiler integration for oxyst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
typst.workspace = true
typst-ide.workspace = true
typst-kit.workspace = true
typst-layout.workspace = true
unicode-segmentation.workspace = true

[lints]
workspace = true
