[package]
name = "oxyst-render"
description = "Typst page rendering for oxyst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
thiserror.workspace = true
typst.workspace = true
typst-pdf.workspace = true
typst-render.workspace = true
typst-svg.workspace = true
oxyst-compiler.workspace = true

[lints]
workspace = true
