[package]
name = "oxyst-app"
description = "Terminal user interface for oxyst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
arboard.workspace = true
crossterm.workspace = true
notify.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
oxyst-compiler.workspace = true
oxyst-config.workspace = true
oxyst-document.workspace = true
oxyst-render.workspace = true
oxyst-theme.workspace = true
typst-syntax.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
