[package]
name = "typst-tui-app"
description = "Terminal user interface for typst-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
thiserror.workspace = true
tokio.workspace = true
typst-tui-compiler.workspace = true
typst-tui-config.workspace = true
typst-tui-document.workspace = true
typst-tui-render.workspace = true
typst-tui-theme.workspace = true
typst-syntax.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
